const activities = [
  {
    title: "Work",
    bgColor: "--Lightorange",
    imgUrl: "./images/icon-work.svg",
    imgAlt: "work icon",
    daily: 5,
    previousDaily: 7,
    weekly: 32,
    previousWeekly: 36,
    monthly: 103,
    previousMonthly: 128,
  },
  {
    title: "Play",
    bgColor: "--Softblue",
    imgUrl: "./images/icon-play.svg",
    imgAlt: "play icon",
    daily: 1,
    previousDaily: 2,
    weekly: 10,
    previousWeekly: 8,
    monthly: 23,
    previousMonthly: 29,
  },
  {
    title: "Study",
    bgColor: "--Lightred",
    imgUrl: "./images/icon-study.svg",
    imgAlt: "study icon",
    daily: 0,
    previousDaily: 1,
    weekly: 4,
    previousWeekly: 7,
    monthly: 13,
    previousMonthly: 19,
  },
  {
    title: "Exercise",
    bgColor: "--Limegreen",
    imgUrl: "./images/icon-exercise.svg",
    imgAlt: "exercise icon",
    daily: 1,
    previousDaily: 1,
    weekly: 4,
    previousWeekly: 4,
    monthly: 11,
    previousMonthly: 18,
  },
  {
    title: "Social",
    bgColor: "--Violet",
    imgUrl: "./images/icon-social.svg",
    imgAlt: "social icon",
    daily: 1,
    previousDaily: 3,
    weekly: 5,
    previousWeekly: 10,
    monthly: 21,
    previousMonthly: 23,
  },
  {
    title: "Self Care",
    bgColor: "--Softorange",
    imgUrl: "./images/icon-self-care.svg",
    imgAlt: "self care icon",
    daily: 0,
    previousDaily: 1,
    weekly: 2,
    previousWeekly: 2,
    monthly: 7,
    previousMonthly: 11,
  },
];

export { activities };
